language: cpp

compiler:
  - clang

cache: apt

before_script:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -y libgflags-dev libgoogle-glog-dev
  - sudo apt-get install -y libstdc++-4.8-dev
  - sudo apt-get install -y ninja-build
  - sudo apt-get install -y cmake

script:
  - ./build/travis.sh
